try {
 timeout(time: 20, unit: 'MINUTES') {
      node("nodejs") {
        stage("Integration tests") {
              newman.runTest("https://raw.githubusercontent.com/sbalajipune/testapp/master/member-service/tests/member-service.postman_collection.json", "https://raw.githubusercontent.com/sbalajipune/testapp/master/member-service/tests/dev.postman_environment.json")
          }
      }
    }
} catch (err) {
 echo "in catch block"
 echo "Caught: ${err}"
 currentBuild.result = 'FAILURE'
 throw err
}